package JavaBasics;

public class FinallyConcept {

	public static void main(String args[]) {
			//test();
		//test2();
          division();		
		}
	
	public static void test() {
		try {
			System.out.println("test inside method");
			throw new RuntimeException("test");
		}catch(Exception e) {
		System.out.println("inside block");
	}
         finally
         {
        	 System.out.println("hduyfdurgry");
         }
}

   //finally method must n should use try catch method


  public static void test2() {
	  try {
		  System.out.println("jfyksdgydc");
	  }
	  finally
	  {
		  System.out.println("jhgvuyfuvdkry");
		  
	  }
  }
  
  public  static void division() {
	  int i = 10;
	  try {
		  System.out.println("ufufugdcf");
		  int k = i/0;
	  }
	  catch(Exception e) {
		  System.out.println("hugfvyvcfy");
		  System.out.println("zero error");
	  }
    finally {
    	System.out.println("jvhjhvjh");
    }
		  	  }
	  
  }











